id: P114EF1A4
initial_creation_type: ocr
source_metadata:
  volumes:
    ec2c8fa1da1d438394c1faa41c5b4822:
      base_file: v052.txt
      image_group_id: I1PD95897
      title: བཅོམ་ལྡན་འདས་ཡོན་ཏན་རིན་པོ་ཆེ་སྡུད་པའི་ཚིགས་སུ་བཅད་པའི་དཀའ་འགྲེལ།
      total_pages: 1426
      volume_number: 52
